package simulation;

 
/**
 * Statistics class is used to report the performance of a node
 * @author Patrick Afotey
 *
 */
public class Statistics {
	// int values generated by a node
	private int sent;
	private int collisions;
	private int received;
	private int retransmitted;
	private int dropped;
	
	/**
	 * takes in the listed int parameters and assigns their values to the field. 
	 * @param sent
	 * @param collisions
	 * @param received
	 * @param retransmitted
	 * @param dropped
	 */
	public Statistics (int sent, int collisions, int received, int retransmitted, int dropped){
		this.sent = sent;
		this.collisions = collisions;
		this.received = received; 
		this.retransmitted = retransmitted;
		this.dropped = dropped;
	}
	
	/**
	 * Returns the recieved statistics
	 * @return int
	 */
	public int getRecieved(){
		return received;
	}
	
	/**
	 * Returns the retransmitted statistics
	 * @return int
	 */
	public int getRetransmitted(){
		return retransmitted;
	}
	
	/**
	 * Returns the sent statistics
	 * @return int
	 */
	public int getSent(){
		return sent;
	}

	/**
	 * Returns the collision statistics
	 * @return int
	 */
	public int getCollisions(){
		return collisions;
	}
	
	/**
	 * Returns the dropped statistics
	 * @return int
	 */
	public int getDropped(){
		return dropped;
	}

	/**
	 * Sets the recieved statistics
	 */
	public void setRecieved(int received){
		this.received = received;
	}
	
	/**
	 * Sets the sent statistics
	 */
	public void setSent(int sent){
		this.sent = sent;
	}

	/**
	 * Sets the collisions statistics
	 */
	public void setCollisions(int collisions){
		this.collisions = collisions;
	}
	
	/**
	 * Sets the retransmitted statistics
	 */
	public void setRetransmitted(int retransmitted){
		this.retransmitted =  retransmitted;
	}
	
	/**
	 * Sets the dropped statistics
	 */
	public void setDropped(int dropped){
		this.dropped = dropped;
	}

	/**
	 * resets the values of the statistics field.
	 */
	public void reset() {
		sent = 0;
		collisions = 0;
		received = 0;
		dropped = 0;
		retransmitted = 0;
	}

	/**
	 * Sums up the values of the parameter statistics
	 * to this statistics objects value.
	 * @param stats
	 */
	public void addStats(Statistics stats) {
		sent = sent + stats.getSent();
		received = received + stats.getRecieved();
		collisions = collisions + stats.getCollisions();
		dropped = dropped + stats.getDropped();
		retransmitted = retransmitted + stats.getRetransmitted();
	}

}
